### ISSUE TITLE
未名messyonline (云墨)的用户意见

### ISSUE THREAD

**Issue by ReaRuiRay** [pku-birdmen/pkuwebmaster#1]
你好，首先感谢大大写的插件~美观又方便
我下载使用以后有如下几个建议：
1. 连接收费地址和免费地址的时候图标是否可以做到有所区别（不知道技术上能不能实
现），这样方便同学知道自己现在连接的是不是收费网
2. 在每次连接收费地址的时候提示信息是否可以加上已用收费时间信息？（一点强迫症
的小要求...
3. 可否推出类似连接收费网页1分钟之后自动断开之类的定制功能？经常连着连着就忘了
断开收费地址了QAQ或者类似的能解决忘记断开功能的都行...

再次感谢~

**Comment by harttle** [comment]
1. 收费/免费/断开的图标区别不适合在Chrome插件中做。因为Chrome插件只知道自己做过哪些操作，而不知现有网络状态如何。如果需要上次操作信息，在点击插件按钮的弹窗底部可以看到。
2. 收费时间已添加，见 #2 
3. 自动断网功能存在易用性和功能性的权衡。在这里（ #3 ）又过尝试但失败了。

**Comment by harttle** [comment]
已支持在不同状态下显示不同按钮图标，见 d24478e7b1c75c4c2f091c4dbde2b54cfe778562
