### ISSUE TITLE
收费网关断网提醒和配置入口

### ISSUE THREAD

**Issue by dusx5** [pku-birdmen/pkuwebmaster#3]
1、当用户连接收费网关时，要关闭浏览器可以弹出窗口提醒用户当前连接收费网关。

2、在 连接到免费、连接到收费、断开所有连接的右下角可以加个设置按钮，进入设置界面，方便用户可  
     以重新绑定账户等设置信息。

```
fuck birdmen！
```

**Comment by harttle** [comment]
- 已添加设置按钮，见： bd371d81666f25fc8a505e25b35b47d10addc351
- Chrome退出事件是不可监听的，见：http://stackoverflow.com/questions/3390470/event-onbrowserclose-for-google-chrome-extension 断开连接需要另想它法
