### ISSUE TITLE
几个无关紧要的小建议

### ISSUE THREAD

**Issue by bitxel** [pku-birdmen/pkuwebmaster#4]
首先感谢作者的辛苦工作！

体验了一下用户体验比官方的要好，出错时候也知道原因了

在此有个小疑问： 
为什么收费时长用匹配字符串的方法来获取，而不用`<!--IPGWCLIENT`中的`FR_TIME`，也就不用单独再写一段代码来获取

可以在readme中提示下配置地址 chrome-extension://bnlipdfmheddpljigcaaamjpnbhhklkb/options/index.html

顺便把chrome商店里的代码更新下到最新吧：）【懒癌发作无药可救 😂

**Comment by harttle** [comment]
感谢支持！已更新README，给出进入『设置页面』的方法。见 48da8f7be91d1d22f4619521a7073fc8139d68e7

现在在用的API中，IPGWCLIENT中没有FR_TIME字段。整个数据是这样的：

```
<!--IPGWCLIENT_START SUCCESS=YES STATE=connected USERNAME=* FIXRATE=YES 
FR_DESC_CN=90元不限时包月 FR_DESC_EN=unlimited SCOPE=international DEFICIT=NO 
CONNECTIONS=2 BALANCE=* IP=* MESSAGE=  IPGWCLIENT_END-->
```

ITS未提供JSON API否则就方便了……如果你有更好的方式可重新打开该Issue。

**Comment by bitxel** [comment]
我看到的是

```
<!--IPGWCLIENT_START SUCCESS=YES STATE=connected USERNAME=. FIXRATE=YES FR_DESC_CN=0元60小时包月 FR_DESC_EN=60hours/0RMB FR_TIME=10.001 SCOPE=domestic CONNECTIONS=1 BALANCE=0.0 IP=10.128.1.84 MESSAGE=  IPGWCLIENT_END-->
```

套餐不同，返回值貌似不一样
